name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 2.3.0-dev.2
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.8.1+4
  device_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.1
  photo_manager: ^1.2.5
  video_player: 2.1.6
